### ISSUE TITLE
[Question]: [Question]: How to make the description box not infinite (not load more) and like normal description box

### ISSUE THREAD

**Issue by HassanSan525** [Mentor404/anilist-css#7]
### What's Your Question?

title

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by carloshdrp** [comment]
You can add the following rule below the imports you are using.

```css
@import url(https://mentor404.github.io/anilist-css/neon.css);
@import......

.user .about .content-wrap {
  max-height: 700px !important;
  overflow-y: scroll !important;
}
```
This overrides the rule from the imports and reverts the maximum size back to the default.
